# Generated by Django 5.0.7 on 2024-07-30 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='full_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='filtered_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='online_shop.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
