# Generated by Django 5.0.7 on 2024-08-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_remove_comment_full_name_comment_filtered_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
